<?php
/**
 * AddressesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  ClickSend
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClickSend\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use ClickSend\ApiException;
use ClickSend\Configuration;
use ClickSend\FormDataProcessor;
use ClickSend\HeaderSelector;
use ClickSend\ObjectSerializer;

/**
 * AddressesApi Class Doc Comment
 *
 * @category Class
 * @package  ClickSend
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddressesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createReturnAddress' => [
            'application/json',
        ],
        'deleteReturnAddress' => [
            'application/json',
        ],
        'updateReturnAddress' => [
            'application/json',
        ],
        'viewSpecificReturnAddress' => [
            'application/json',
        ],
        'viewYourReturnAddresses' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createReturnAddress
     *
     * Create Return Address
     *
     * @param  string|null $content_type content_type (optional)
     * @param  \ClickSend\Model\CreateReturnAddressRequest|null $create_return_address_request create_return_address_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createReturnAddress'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClickSend\Model\CreateReturnAddress
     */
    public function createReturnAddress($content_type = null, $create_return_address_request = null, string $contentType = self::contentTypes['createReturnAddress'][0])
    {
        list($response) = $this->createReturnAddressWithHttpInfo($content_type, $create_return_address_request, $contentType);
        return $response;
    }

    /**
     * Operation createReturnAddressWithHttpInfo
     *
     * Create Return Address
     *
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\CreateReturnAddressRequest|null $create_return_address_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createReturnAddress'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClickSend\Model\CreateReturnAddress, HTTP status code, HTTP response headers (array of strings)
     */
    public function createReturnAddressWithHttpInfo($content_type = null, $create_return_address_request = null, string $contentType = self::contentTypes['createReturnAddress'][0])
    {
        $request = $this->createReturnAddressRequest($content_type, $create_return_address_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClickSend\Model\CreateReturnAddress',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClickSend\Model\CreateReturnAddress',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClickSend\Model\CreateReturnAddress',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createReturnAddressAsync
     *
     * Create Return Address
     *
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\CreateReturnAddressRequest|null $create_return_address_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createReturnAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createReturnAddressAsync($content_type = null, $create_return_address_request = null, string $contentType = self::contentTypes['createReturnAddress'][0])
    {
        return $this->createReturnAddressAsyncWithHttpInfo($content_type, $create_return_address_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createReturnAddressAsyncWithHttpInfo
     *
     * Create Return Address
     *
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\CreateReturnAddressRequest|null $create_return_address_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createReturnAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createReturnAddressAsyncWithHttpInfo($content_type = null, $create_return_address_request = null, string $contentType = self::contentTypes['createReturnAddress'][0])
    {
        $returnType = '\ClickSend\Model\CreateReturnAddress';
        $request = $this->createReturnAddressRequest($content_type, $create_return_address_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createReturnAddress'
     *
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\CreateReturnAddressRequest|null $create_return_address_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createReturnAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createReturnAddressRequest($content_type = null, $create_return_address_request = null, string $contentType = self::contentTypes['createReturnAddress'][0])
    {




        $resourcePath = '/v3/post/return-addresses';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_return_address_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_return_address_request));
            } else {
                $httpBody = $create_return_address_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteReturnAddress
     *
     * Delete Return Address
     *
     * @param  string $return_address_id return_address_id (required)
     * @param  string|null $content_type content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteReturnAddress'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClickSend\Model\DeleteReturnAddress
     */
    public function deleteReturnAddress($return_address_id, $content_type = null, string $contentType = self::contentTypes['deleteReturnAddress'][0])
    {
        list($response) = $this->deleteReturnAddressWithHttpInfo($return_address_id, $content_type, $contentType);
        return $response;
    }

    /**
     * Operation deleteReturnAddressWithHttpInfo
     *
     * Delete Return Address
     *
     * @param  string $return_address_id (required)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteReturnAddress'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClickSend\Model\DeleteReturnAddress, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteReturnAddressWithHttpInfo($return_address_id, $content_type = null, string $contentType = self::contentTypes['deleteReturnAddress'][0])
    {
        $request = $this->deleteReturnAddressRequest($return_address_id, $content_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClickSend\Model\DeleteReturnAddress',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClickSend\Model\DeleteReturnAddress',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClickSend\Model\DeleteReturnAddress',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteReturnAddressAsync
     *
     * Delete Return Address
     *
     * @param  string $return_address_id (required)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteReturnAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteReturnAddressAsync($return_address_id, $content_type = null, string $contentType = self::contentTypes['deleteReturnAddress'][0])
    {
        return $this->deleteReturnAddressAsyncWithHttpInfo($return_address_id, $content_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteReturnAddressAsyncWithHttpInfo
     *
     * Delete Return Address
     *
     * @param  string $return_address_id (required)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteReturnAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteReturnAddressAsyncWithHttpInfo($return_address_id, $content_type = null, string $contentType = self::contentTypes['deleteReturnAddress'][0])
    {
        $returnType = '\ClickSend\Model\DeleteReturnAddress';
        $request = $this->deleteReturnAddressRequest($return_address_id, $content_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteReturnAddress'
     *
     * @param  string $return_address_id (required)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteReturnAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteReturnAddressRequest($return_address_id, $content_type = null, string $contentType = self::contentTypes['deleteReturnAddress'][0])
    {

        // verify the required parameter 'return_address_id' is set
        if ($return_address_id === null || (is_array($return_address_id) && count($return_address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $return_address_id when calling deleteReturnAddress'
            );
        }



        $resourcePath = '/v3/post/return-addresses/{return_address_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($return_address_id !== null) {
            $resourcePath = str_replace(
                '{return_address_id}',
                ObjectSerializer::toPathValue($return_address_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateReturnAddress
     *
     * Update Return Address
     *
     * @param  string $return_address_id return_address_id (required)
     * @param  string|null $content_type content_type (optional)
     * @param  \ClickSend\Model\UpdateReturnAddressRequest|null $update_return_address_request update_return_address_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateReturnAddress'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClickSend\Model\UpdateReturnAddress
     */
    public function updateReturnAddress($return_address_id, $content_type = null, $update_return_address_request = null, string $contentType = self::contentTypes['updateReturnAddress'][0])
    {
        list($response) = $this->updateReturnAddressWithHttpInfo($return_address_id, $content_type, $update_return_address_request, $contentType);
        return $response;
    }

    /**
     * Operation updateReturnAddressWithHttpInfo
     *
     * Update Return Address
     *
     * @param  string $return_address_id (required)
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\UpdateReturnAddressRequest|null $update_return_address_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateReturnAddress'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClickSend\Model\UpdateReturnAddress, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateReturnAddressWithHttpInfo($return_address_id, $content_type = null, $update_return_address_request = null, string $contentType = self::contentTypes['updateReturnAddress'][0])
    {
        $request = $this->updateReturnAddressRequest($return_address_id, $content_type, $update_return_address_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClickSend\Model\UpdateReturnAddress',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClickSend\Model\UpdateReturnAddress',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClickSend\Model\UpdateReturnAddress',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation updateReturnAddressAsync
     *
     * Update Return Address
     *
     * @param  string $return_address_id (required)
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\UpdateReturnAddressRequest|null $update_return_address_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateReturnAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateReturnAddressAsync($return_address_id, $content_type = null, $update_return_address_request = null, string $contentType = self::contentTypes['updateReturnAddress'][0])
    {
        return $this->updateReturnAddressAsyncWithHttpInfo($return_address_id, $content_type, $update_return_address_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateReturnAddressAsyncWithHttpInfo
     *
     * Update Return Address
     *
     * @param  string $return_address_id (required)
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\UpdateReturnAddressRequest|null $update_return_address_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateReturnAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateReturnAddressAsyncWithHttpInfo($return_address_id, $content_type = null, $update_return_address_request = null, string $contentType = self::contentTypes['updateReturnAddress'][0])
    {
        $returnType = '\ClickSend\Model\UpdateReturnAddress';
        $request = $this->updateReturnAddressRequest($return_address_id, $content_type, $update_return_address_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateReturnAddress'
     *
     * @param  string $return_address_id (required)
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\UpdateReturnAddressRequest|null $update_return_address_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateReturnAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateReturnAddressRequest($return_address_id, $content_type = null, $update_return_address_request = null, string $contentType = self::contentTypes['updateReturnAddress'][0])
    {

        // verify the required parameter 'return_address_id' is set
        if ($return_address_id === null || (is_array($return_address_id) && count($return_address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $return_address_id when calling updateReturnAddress'
            );
        }




        $resourcePath = '/v3/post/return-addresses/{return_address_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($return_address_id !== null) {
            $resourcePath = str_replace(
                '{return_address_id}',
                ObjectSerializer::toPathValue($return_address_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_return_address_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_return_address_request));
            } else {
                $httpBody = $update_return_address_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation viewSpecificReturnAddress
     *
     * View Specific Return Address
     *
     * @param  string $return_address_id return_address_id (required)
     * @param  string|null $content_type content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewSpecificReturnAddress'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClickSend\Model\ViewSpecificReturnAddress
     */
    public function viewSpecificReturnAddress($return_address_id, $content_type = null, string $contentType = self::contentTypes['viewSpecificReturnAddress'][0])
    {
        list($response) = $this->viewSpecificReturnAddressWithHttpInfo($return_address_id, $content_type, $contentType);
        return $response;
    }

    /**
     * Operation viewSpecificReturnAddressWithHttpInfo
     *
     * View Specific Return Address
     *
     * @param  string $return_address_id (required)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewSpecificReturnAddress'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClickSend\Model\ViewSpecificReturnAddress, HTTP status code, HTTP response headers (array of strings)
     */
    public function viewSpecificReturnAddressWithHttpInfo($return_address_id, $content_type = null, string $contentType = self::contentTypes['viewSpecificReturnAddress'][0])
    {
        $request = $this->viewSpecificReturnAddressRequest($return_address_id, $content_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClickSend\Model\ViewSpecificReturnAddress',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClickSend\Model\ViewSpecificReturnAddress',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClickSend\Model\ViewSpecificReturnAddress',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation viewSpecificReturnAddressAsync
     *
     * View Specific Return Address
     *
     * @param  string $return_address_id (required)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewSpecificReturnAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function viewSpecificReturnAddressAsync($return_address_id, $content_type = null, string $contentType = self::contentTypes['viewSpecificReturnAddress'][0])
    {
        return $this->viewSpecificReturnAddressAsyncWithHttpInfo($return_address_id, $content_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation viewSpecificReturnAddressAsyncWithHttpInfo
     *
     * View Specific Return Address
     *
     * @param  string $return_address_id (required)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewSpecificReturnAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function viewSpecificReturnAddressAsyncWithHttpInfo($return_address_id, $content_type = null, string $contentType = self::contentTypes['viewSpecificReturnAddress'][0])
    {
        $returnType = '\ClickSend\Model\ViewSpecificReturnAddress';
        $request = $this->viewSpecificReturnAddressRequest($return_address_id, $content_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'viewSpecificReturnAddress'
     *
     * @param  string $return_address_id (required)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewSpecificReturnAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function viewSpecificReturnAddressRequest($return_address_id, $content_type = null, string $contentType = self::contentTypes['viewSpecificReturnAddress'][0])
    {

        // verify the required parameter 'return_address_id' is set
        if ($return_address_id === null || (is_array($return_address_id) && count($return_address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $return_address_id when calling viewSpecificReturnAddress'
            );
        }



        $resourcePath = '/v3/post/return-addresses/{return_address_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($return_address_id !== null) {
            $resourcePath = str_replace(
                '{return_address_id}',
                ObjectSerializer::toPathValue($return_address_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation viewYourReturnAddresses
     *
     * View Your Return Addresses
     *
     * @param  string|null $content_type content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewYourReturnAddresses'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClickSend\Model\ViewYourReturnAddresses
     */
    public function viewYourReturnAddresses($content_type = null, string $contentType = self::contentTypes['viewYourReturnAddresses'][0])
    {
        list($response) = $this->viewYourReturnAddressesWithHttpInfo($content_type, $contentType);
        return $response;
    }

    /**
     * Operation viewYourReturnAddressesWithHttpInfo
     *
     * View Your Return Addresses
     *
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewYourReturnAddresses'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClickSend\Model\ViewYourReturnAddresses, HTTP status code, HTTP response headers (array of strings)
     */
    public function viewYourReturnAddressesWithHttpInfo($content_type = null, string $contentType = self::contentTypes['viewYourReturnAddresses'][0])
    {
        $request = $this->viewYourReturnAddressesRequest($content_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClickSend\Model\ViewYourReturnAddresses',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClickSend\Model\ViewYourReturnAddresses',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClickSend\Model\ViewYourReturnAddresses',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation viewYourReturnAddressesAsync
     *
     * View Your Return Addresses
     *
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewYourReturnAddresses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function viewYourReturnAddressesAsync($content_type = null, string $contentType = self::contentTypes['viewYourReturnAddresses'][0])
    {
        return $this->viewYourReturnAddressesAsyncWithHttpInfo($content_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation viewYourReturnAddressesAsyncWithHttpInfo
     *
     * View Your Return Addresses
     *
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewYourReturnAddresses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function viewYourReturnAddressesAsyncWithHttpInfo($content_type = null, string $contentType = self::contentTypes['viewYourReturnAddresses'][0])
    {
        $returnType = '\ClickSend\Model\ViewYourReturnAddresses';
        $request = $this->viewYourReturnAddressesRequest($content_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'viewYourReturnAddresses'
     *
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewYourReturnAddresses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function viewYourReturnAddressesRequest($content_type = null, string $contentType = self::contentTypes['viewYourReturnAddresses'][0])
    {



        $resourcePath = '/v3/post/return-addresses';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
