<?php
/**
 * VoiceMessagingApi
 * PHP version 8.1
 *
 * @category Class
 * @package  ClickSend
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClickSend\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use ClickSend\ApiException;
use ClickSend\Configuration;
use ClickSend\FormDataProcessor;
use ClickSend\HeaderSelector;
use ClickSend\ObjectSerializer;

/**
 * VoiceMessagingApi Class Doc Comment
 *
 * @category Class
 * @package  ClickSend
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VoiceMessagingApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'calculateVoicePrice' => [
            'application/json',
        ],
        'cancelAllVoiceMessages' => [
            'application/json',
        ],
        'cancelVoiceMessage' => [
            'application/json',
        ],
        'exportVoiceHistory' => [
            'application/json',
        ],
        'getVoiceHistory' => [
            'application/json',
        ],
        'sendVoiceMessage' => [
            'application/json',
        ],
        'viewVoiceLanguages' => [
            'application/json',
        ],
        'viewVoiceReceipts' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation calculateVoicePrice
     *
     * Calculate Voice Price
     *
     * @param  string|null $content_type content_type (optional)
     * @param  \ClickSend\Model\CalculateVoicePriceRequest|null $calculate_voice_price_request calculate_voice_price_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['calculateVoicePrice'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClickSend\Model\CalculateVoicePrice
     */
    public function calculateVoicePrice($content_type = null, $calculate_voice_price_request = null, string $contentType = self::contentTypes['calculateVoicePrice'][0])
    {
        list($response) = $this->calculateVoicePriceWithHttpInfo($content_type, $calculate_voice_price_request, $contentType);
        return $response;
    }

    /**
     * Operation calculateVoicePriceWithHttpInfo
     *
     * Calculate Voice Price
     *
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\CalculateVoicePriceRequest|null $calculate_voice_price_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['calculateVoicePrice'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClickSend\Model\CalculateVoicePrice, HTTP status code, HTTP response headers (array of strings)
     */
    public function calculateVoicePriceWithHttpInfo($content_type = null, $calculate_voice_price_request = null, string $contentType = self::contentTypes['calculateVoicePrice'][0])
    {
        $request = $this->calculateVoicePriceRequest($content_type, $calculate_voice_price_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClickSend\Model\CalculateVoicePrice',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClickSend\Model\CalculateVoicePrice',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClickSend\Model\CalculateVoicePrice',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation calculateVoicePriceAsync
     *
     * Calculate Voice Price
     *
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\CalculateVoicePriceRequest|null $calculate_voice_price_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['calculateVoicePrice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function calculateVoicePriceAsync($content_type = null, $calculate_voice_price_request = null, string $contentType = self::contentTypes['calculateVoicePrice'][0])
    {
        return $this->calculateVoicePriceAsyncWithHttpInfo($content_type, $calculate_voice_price_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation calculateVoicePriceAsyncWithHttpInfo
     *
     * Calculate Voice Price
     *
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\CalculateVoicePriceRequest|null $calculate_voice_price_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['calculateVoicePrice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function calculateVoicePriceAsyncWithHttpInfo($content_type = null, $calculate_voice_price_request = null, string $contentType = self::contentTypes['calculateVoicePrice'][0])
    {
        $returnType = '\ClickSend\Model\CalculateVoicePrice';
        $request = $this->calculateVoicePriceRequest($content_type, $calculate_voice_price_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'calculateVoicePrice'
     *
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\CalculateVoicePriceRequest|null $calculate_voice_price_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['calculateVoicePrice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function calculateVoicePriceRequest($content_type = null, $calculate_voice_price_request = null, string $contentType = self::contentTypes['calculateVoicePrice'][0])
    {




        $resourcePath = '/v3/voice/price';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($calculate_voice_price_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($calculate_voice_price_request));
            } else {
                $httpBody = $calculate_voice_price_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation cancelAllVoiceMessages
     *
     * Cancel All Voice Messages
     *
     * @param  string|null $content_type content_type (optional)
     * @param  object|null $body body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelAllVoiceMessages'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClickSend\Model\CancelAllVoiceMessages
     */
    public function cancelAllVoiceMessages($content_type = null, $body = null, string $contentType = self::contentTypes['cancelAllVoiceMessages'][0])
    {
        list($response) = $this->cancelAllVoiceMessagesWithHttpInfo($content_type, $body, $contentType);
        return $response;
    }

    /**
     * Operation cancelAllVoiceMessagesWithHttpInfo
     *
     * Cancel All Voice Messages
     *
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelAllVoiceMessages'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClickSend\Model\CancelAllVoiceMessages, HTTP status code, HTTP response headers (array of strings)
     */
    public function cancelAllVoiceMessagesWithHttpInfo($content_type = null, $body = null, string $contentType = self::contentTypes['cancelAllVoiceMessages'][0])
    {
        $request = $this->cancelAllVoiceMessagesRequest($content_type, $body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClickSend\Model\CancelAllVoiceMessages',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClickSend\Model\CancelAllVoiceMessages',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClickSend\Model\CancelAllVoiceMessages',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation cancelAllVoiceMessagesAsync
     *
     * Cancel All Voice Messages
     *
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelAllVoiceMessages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelAllVoiceMessagesAsync($content_type = null, $body = null, string $contentType = self::contentTypes['cancelAllVoiceMessages'][0])
    {
        return $this->cancelAllVoiceMessagesAsyncWithHttpInfo($content_type, $body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation cancelAllVoiceMessagesAsyncWithHttpInfo
     *
     * Cancel All Voice Messages
     *
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelAllVoiceMessages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelAllVoiceMessagesAsyncWithHttpInfo($content_type = null, $body = null, string $contentType = self::contentTypes['cancelAllVoiceMessages'][0])
    {
        $returnType = '\ClickSend\Model\CancelAllVoiceMessages';
        $request = $this->cancelAllVoiceMessagesRequest($content_type, $body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'cancelAllVoiceMessages'
     *
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelAllVoiceMessages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function cancelAllVoiceMessagesRequest($content_type = null, $body = null, string $contentType = self::contentTypes['cancelAllVoiceMessages'][0])
    {




        $resourcePath = '/v3/voice/cancel-all';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation cancelVoiceMessage
     *
     * Cancel Voice Message
     *
     * @param  string $message_id message_id (required)
     * @param  string|null $content_type content_type (optional)
     * @param  object|null $body body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelVoiceMessage'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClickSend\Model\CancelVoiceMessage
     */
    public function cancelVoiceMessage($message_id, $content_type = null, $body = null, string $contentType = self::contentTypes['cancelVoiceMessage'][0])
    {
        list($response) = $this->cancelVoiceMessageWithHttpInfo($message_id, $content_type, $body, $contentType);
        return $response;
    }

    /**
     * Operation cancelVoiceMessageWithHttpInfo
     *
     * Cancel Voice Message
     *
     * @param  string $message_id (required)
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelVoiceMessage'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClickSend\Model\CancelVoiceMessage, HTTP status code, HTTP response headers (array of strings)
     */
    public function cancelVoiceMessageWithHttpInfo($message_id, $content_type = null, $body = null, string $contentType = self::contentTypes['cancelVoiceMessage'][0])
    {
        $request = $this->cancelVoiceMessageRequest($message_id, $content_type, $body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClickSend\Model\CancelVoiceMessage',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClickSend\Model\CancelVoiceMessage',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClickSend\Model\CancelVoiceMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation cancelVoiceMessageAsync
     *
     * Cancel Voice Message
     *
     * @param  string $message_id (required)
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelVoiceMessage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelVoiceMessageAsync($message_id, $content_type = null, $body = null, string $contentType = self::contentTypes['cancelVoiceMessage'][0])
    {
        return $this->cancelVoiceMessageAsyncWithHttpInfo($message_id, $content_type, $body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation cancelVoiceMessageAsyncWithHttpInfo
     *
     * Cancel Voice Message
     *
     * @param  string $message_id (required)
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelVoiceMessage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelVoiceMessageAsyncWithHttpInfo($message_id, $content_type = null, $body = null, string $contentType = self::contentTypes['cancelVoiceMessage'][0])
    {
        $returnType = '\ClickSend\Model\CancelVoiceMessage';
        $request = $this->cancelVoiceMessageRequest($message_id, $content_type, $body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'cancelVoiceMessage'
     *
     * @param  string $message_id (required)
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelVoiceMessage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function cancelVoiceMessageRequest($message_id, $content_type = null, $body = null, string $contentType = self::contentTypes['cancelVoiceMessage'][0])
    {

        // verify the required parameter 'message_id' is set
        if ($message_id === null || (is_array($message_id) && count($message_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $message_id when calling cancelVoiceMessage'
            );
        }




        $resourcePath = '/v3/voice/{message_id}/cancel';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($message_id !== null) {
            $resourcePath = str_replace(
                '{message_id}',
                ObjectSerializer::toPathValue($message_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation exportVoiceHistory
     *
     * Export Voice History
     *
     * @param  string|null $content_type content_type (optional)
     * @param  string|null $filename filename (optional)
     * @param  string|null $q q (optional)
     * @param  string|null $order_by order_by (optional)
     * @param  string|null $date_from date_from (optional)
     * @param  string|null $date_to date_to (optional)
     * @param  int|null $limit limit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exportVoiceHistory'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClickSend\Model\ExportVoiceHistory
     */
    public function exportVoiceHistory($content_type = null, $filename = null, $q = null, $order_by = null, $date_from = null, $date_to = null, $limit = null, string $contentType = self::contentTypes['exportVoiceHistory'][0])
    {
        list($response) = $this->exportVoiceHistoryWithHttpInfo($content_type, $filename, $q, $order_by, $date_from, $date_to, $limit, $contentType);
        return $response;
    }

    /**
     * Operation exportVoiceHistoryWithHttpInfo
     *
     * Export Voice History
     *
     * @param  string|null $content_type (optional)
     * @param  string|null $filename (optional)
     * @param  string|null $q (optional)
     * @param  string|null $order_by (optional)
     * @param  string|null $date_from (optional)
     * @param  string|null $date_to (optional)
     * @param  int|null $limit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exportVoiceHistory'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClickSend\Model\ExportVoiceHistory, HTTP status code, HTTP response headers (array of strings)
     */
    public function exportVoiceHistoryWithHttpInfo($content_type = null, $filename = null, $q = null, $order_by = null, $date_from = null, $date_to = null, $limit = null, string $contentType = self::contentTypes['exportVoiceHistory'][0])
    {
        $request = $this->exportVoiceHistoryRequest($content_type, $filename, $q, $order_by, $date_from, $date_to, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClickSend\Model\ExportVoiceHistory',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClickSend\Model\ExportVoiceHistory',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClickSend\Model\ExportVoiceHistory',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation exportVoiceHistoryAsync
     *
     * Export Voice History
     *
     * @param  string|null $content_type (optional)
     * @param  string|null $filename (optional)
     * @param  string|null $q (optional)
     * @param  string|null $order_by (optional)
     * @param  string|null $date_from (optional)
     * @param  string|null $date_to (optional)
     * @param  int|null $limit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exportVoiceHistory'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function exportVoiceHistoryAsync($content_type = null, $filename = null, $q = null, $order_by = null, $date_from = null, $date_to = null, $limit = null, string $contentType = self::contentTypes['exportVoiceHistory'][0])
    {
        return $this->exportVoiceHistoryAsyncWithHttpInfo($content_type, $filename, $q, $order_by, $date_from, $date_to, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation exportVoiceHistoryAsyncWithHttpInfo
     *
     * Export Voice History
     *
     * @param  string|null $content_type (optional)
     * @param  string|null $filename (optional)
     * @param  string|null $q (optional)
     * @param  string|null $order_by (optional)
     * @param  string|null $date_from (optional)
     * @param  string|null $date_to (optional)
     * @param  int|null $limit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exportVoiceHistory'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function exportVoiceHistoryAsyncWithHttpInfo($content_type = null, $filename = null, $q = null, $order_by = null, $date_from = null, $date_to = null, $limit = null, string $contentType = self::contentTypes['exportVoiceHistory'][0])
    {
        $returnType = '\ClickSend\Model\ExportVoiceHistory';
        $request = $this->exportVoiceHistoryRequest($content_type, $filename, $q, $order_by, $date_from, $date_to, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'exportVoiceHistory'
     *
     * @param  string|null $content_type (optional)
     * @param  string|null $filename (optional)
     * @param  string|null $q (optional)
     * @param  string|null $order_by (optional)
     * @param  string|null $date_from (optional)
     * @param  string|null $date_to (optional)
     * @param  int|null $limit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exportVoiceHistory'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function exportVoiceHistoryRequest($content_type = null, $filename = null, $q = null, $order_by = null, $date_from = null, $date_to = null, $limit = null, string $contentType = self::contentTypes['exportVoiceHistory'][0])
    {









        $resourcePath = '/v3/voice/history/export';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filename,
            'filename', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $q,
            'q', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order_by,
            'order_by', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_from,
            'date_from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_to,
            'date_to', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getVoiceHistory
     *
     * Get Voice History
     *
     * @param  string|null $content_type content_type (optional)
     * @param  string|null $date_to date_to (optional)
     * @param  int|null $limit limit (optional)
     * @param  string|null $operator operator (optional)
     * @param  string|null $order_by order_by (optional)
     * @param  int|null $page page (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVoiceHistory'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClickSend\Model\GetVoiceHistory
     */
    public function getVoiceHistory($content_type = null, $date_to = null, $limit = null, $operator = null, $order_by = null, $page = null, string $contentType = self::contentTypes['getVoiceHistory'][0])
    {
        list($response) = $this->getVoiceHistoryWithHttpInfo($content_type, $date_to, $limit, $operator, $order_by, $page, $contentType);
        return $response;
    }

    /**
     * Operation getVoiceHistoryWithHttpInfo
     *
     * Get Voice History
     *
     * @param  string|null $content_type (optional)
     * @param  string|null $date_to (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $operator (optional)
     * @param  string|null $order_by (optional)
     * @param  int|null $page (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVoiceHistory'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClickSend\Model\GetVoiceHistory, HTTP status code, HTTP response headers (array of strings)
     */
    public function getVoiceHistoryWithHttpInfo($content_type = null, $date_to = null, $limit = null, $operator = null, $order_by = null, $page = null, string $contentType = self::contentTypes['getVoiceHistory'][0])
    {
        $request = $this->getVoiceHistoryRequest($content_type, $date_to, $limit, $operator, $order_by, $page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClickSend\Model\GetVoiceHistory',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClickSend\Model\GetVoiceHistory',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClickSend\Model\GetVoiceHistory',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getVoiceHistoryAsync
     *
     * Get Voice History
     *
     * @param  string|null $content_type (optional)
     * @param  string|null $date_to (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $operator (optional)
     * @param  string|null $order_by (optional)
     * @param  int|null $page (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVoiceHistory'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVoiceHistoryAsync($content_type = null, $date_to = null, $limit = null, $operator = null, $order_by = null, $page = null, string $contentType = self::contentTypes['getVoiceHistory'][0])
    {
        return $this->getVoiceHistoryAsyncWithHttpInfo($content_type, $date_to, $limit, $operator, $order_by, $page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getVoiceHistoryAsyncWithHttpInfo
     *
     * Get Voice History
     *
     * @param  string|null $content_type (optional)
     * @param  string|null $date_to (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $operator (optional)
     * @param  string|null $order_by (optional)
     * @param  int|null $page (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVoiceHistory'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVoiceHistoryAsyncWithHttpInfo($content_type = null, $date_to = null, $limit = null, $operator = null, $order_by = null, $page = null, string $contentType = self::contentTypes['getVoiceHistory'][0])
    {
        $returnType = '\ClickSend\Model\GetVoiceHistory';
        $request = $this->getVoiceHistoryRequest($content_type, $date_to, $limit, $operator, $order_by, $page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getVoiceHistory'
     *
     * @param  string|null $content_type (optional)
     * @param  string|null $date_to (optional)
     * @param  int|null $limit (optional)
     * @param  string|null $operator (optional)
     * @param  string|null $order_by (optional)
     * @param  int|null $page (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVoiceHistory'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getVoiceHistoryRequest($content_type = null, $date_to = null, $limit = null, $operator = null, $order_by = null, $page = null, string $contentType = self::contentTypes['getVoiceHistory'][0])
    {








        $resourcePath = '/v3/voice/history';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_to,
            'date_to', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $operator,
            'operator', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order_by,
            'order_by', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendVoiceMessage
     *
     * Send Voice Message
     *
     * @param  string|null $content_type content_type (optional)
     * @param  \ClickSend\Model\SendVoiceMessageRequest|null $send_voice_message_request send_voice_message_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoiceMessage'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClickSend\Model\SendVoiceMessage
     */
    public function sendVoiceMessage($content_type = null, $send_voice_message_request = null, string $contentType = self::contentTypes['sendVoiceMessage'][0])
    {
        list($response) = $this->sendVoiceMessageWithHttpInfo($content_type, $send_voice_message_request, $contentType);
        return $response;
    }

    /**
     * Operation sendVoiceMessageWithHttpInfo
     *
     * Send Voice Message
     *
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\SendVoiceMessageRequest|null $send_voice_message_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoiceMessage'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClickSend\Model\SendVoiceMessage, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendVoiceMessageWithHttpInfo($content_type = null, $send_voice_message_request = null, string $contentType = self::contentTypes['sendVoiceMessage'][0])
    {
        $request = $this->sendVoiceMessageRequest($content_type, $send_voice_message_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClickSend\Model\SendVoiceMessage',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClickSend\Model\SendVoiceMessage',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClickSend\Model\SendVoiceMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation sendVoiceMessageAsync
     *
     * Send Voice Message
     *
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\SendVoiceMessageRequest|null $send_voice_message_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoiceMessage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendVoiceMessageAsync($content_type = null, $send_voice_message_request = null, string $contentType = self::contentTypes['sendVoiceMessage'][0])
    {
        return $this->sendVoiceMessageAsyncWithHttpInfo($content_type, $send_voice_message_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendVoiceMessageAsyncWithHttpInfo
     *
     * Send Voice Message
     *
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\SendVoiceMessageRequest|null $send_voice_message_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoiceMessage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendVoiceMessageAsyncWithHttpInfo($content_type = null, $send_voice_message_request = null, string $contentType = self::contentTypes['sendVoiceMessage'][0])
    {
        $returnType = '\ClickSend\Model\SendVoiceMessage';
        $request = $this->sendVoiceMessageRequest($content_type, $send_voice_message_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendVoiceMessage'
     *
     * @param  string|null $content_type (optional)
     * @param  \ClickSend\Model\SendVoiceMessageRequest|null $send_voice_message_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendVoiceMessage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendVoiceMessageRequest($content_type = null, $send_voice_message_request = null, string $contentType = self::contentTypes['sendVoiceMessage'][0])
    {




        $resourcePath = '/v3/voice/send';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($send_voice_message_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($send_voice_message_request));
            } else {
                $httpBody = $send_voice_message_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation viewVoiceLanguages
     *
     * View Voice Languages
     *
     * @param  string|null $content_type content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewVoiceLanguages'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClickSend\Model\ViewVoiceLanguages
     */
    public function viewVoiceLanguages($content_type = null, string $contentType = self::contentTypes['viewVoiceLanguages'][0])
    {
        list($response) = $this->viewVoiceLanguagesWithHttpInfo($content_type, $contentType);
        return $response;
    }

    /**
     * Operation viewVoiceLanguagesWithHttpInfo
     *
     * View Voice Languages
     *
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewVoiceLanguages'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClickSend\Model\ViewVoiceLanguages, HTTP status code, HTTP response headers (array of strings)
     */
    public function viewVoiceLanguagesWithHttpInfo($content_type = null, string $contentType = self::contentTypes['viewVoiceLanguages'][0])
    {
        $request = $this->viewVoiceLanguagesRequest($content_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClickSend\Model\ViewVoiceLanguages',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClickSend\Model\ViewVoiceLanguages',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClickSend\Model\ViewVoiceLanguages',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation viewVoiceLanguagesAsync
     *
     * View Voice Languages
     *
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewVoiceLanguages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function viewVoiceLanguagesAsync($content_type = null, string $contentType = self::contentTypes['viewVoiceLanguages'][0])
    {
        return $this->viewVoiceLanguagesAsyncWithHttpInfo($content_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation viewVoiceLanguagesAsyncWithHttpInfo
     *
     * View Voice Languages
     *
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewVoiceLanguages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function viewVoiceLanguagesAsyncWithHttpInfo($content_type = null, string $contentType = self::contentTypes['viewVoiceLanguages'][0])
    {
        $returnType = '\ClickSend\Model\ViewVoiceLanguages';
        $request = $this->viewVoiceLanguagesRequest($content_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'viewVoiceLanguages'
     *
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewVoiceLanguages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function viewVoiceLanguagesRequest($content_type = null, string $contentType = self::contentTypes['viewVoiceLanguages'][0])
    {



        $resourcePath = '/v3/voice/lang';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation viewVoiceReceipts
     *
     * View Voice Receipts
     *
     * @param  string|null $content_type content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewVoiceReceipts'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClickSend\Model\ViewVoiceReceipts
     */
    public function viewVoiceReceipts($content_type = null, string $contentType = self::contentTypes['viewVoiceReceipts'][0])
    {
        list($response) = $this->viewVoiceReceiptsWithHttpInfo($content_type, $contentType);
        return $response;
    }

    /**
     * Operation viewVoiceReceiptsWithHttpInfo
     *
     * View Voice Receipts
     *
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewVoiceReceipts'] to see the possible values for this operation
     *
     * @throws \ClickSend\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClickSend\Model\ViewVoiceReceipts, HTTP status code, HTTP response headers (array of strings)
     */
    public function viewVoiceReceiptsWithHttpInfo($content_type = null, string $contentType = self::contentTypes['viewVoiceReceipts'][0])
    {
        $request = $this->viewVoiceReceiptsRequest($content_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClickSend\Model\ViewVoiceReceipts',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClickSend\Model\ViewVoiceReceipts',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClickSend\Model\ViewVoiceReceipts',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation viewVoiceReceiptsAsync
     *
     * View Voice Receipts
     *
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewVoiceReceipts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function viewVoiceReceiptsAsync($content_type = null, string $contentType = self::contentTypes['viewVoiceReceipts'][0])
    {
        return $this->viewVoiceReceiptsAsyncWithHttpInfo($content_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation viewVoiceReceiptsAsyncWithHttpInfo
     *
     * View Voice Receipts
     *
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewVoiceReceipts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function viewVoiceReceiptsAsyncWithHttpInfo($content_type = null, string $contentType = self::contentTypes['viewVoiceReceipts'][0])
    {
        $returnType = '\ClickSend\Model\ViewVoiceReceipts';
        $request = $this->viewVoiceReceiptsRequest($content_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'viewVoiceReceipts'
     *
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['viewVoiceReceipts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function viewVoiceReceiptsRequest($content_type = null, string $contentType = self::contentTypes['viewVoiceReceipts'][0])
    {



        $resourcePath = '/v3/voice/receipts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
