<?php
/**
 * BuyNumberRequestRegistrationData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClickSend
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClickSend\Model;

use \ArrayAccess;
use \ClickSend\ObjectSerializer;

/**
 * BuyNumberRequestRegistrationData Class Doc Comment
 *
 * @category Class
 * @description Optional registration data for number compliance
 * @package  ClickSend
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BuyNumberRequestRegistrationData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'buy_number_request_registration_data';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'business_name' => 'string',
        'business_address' => 'string',
        'suburb' => 'string',
        'postcode' => 'string',
        'state' => 'string',
        'contact_name' => 'string',
        'contact_number' => 'string',
        'country' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'business_name' => null,
        'business_address' => null,
        'suburb' => null,
        'postcode' => null,
        'state' => null,
        'contact_name' => null,
        'contact_number' => null,
        'country' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'business_name' => false,
        'business_address' => false,
        'suburb' => false,
        'postcode' => false,
        'state' => false,
        'contact_name' => false,
        'contact_number' => false,
        'country' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'business_name' => 'business_name',
        'business_address' => 'business_address',
        'suburb' => 'suburb',
        'postcode' => 'postcode',
        'state' => 'state',
        'contact_name' => 'contact_name',
        'contact_number' => 'contact_number',
        'country' => 'country'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'business_name' => 'setBusinessName',
        'business_address' => 'setBusinessAddress',
        'suburb' => 'setSuburb',
        'postcode' => 'setPostcode',
        'state' => 'setState',
        'contact_name' => 'setContactName',
        'contact_number' => 'setContactNumber',
        'country' => 'setCountry'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'business_name' => 'getBusinessName',
        'business_address' => 'getBusinessAddress',
        'suburb' => 'getSuburb',
        'postcode' => 'getPostcode',
        'state' => 'getState',
        'contact_name' => 'getContactName',
        'contact_number' => 'getContactNumber',
        'country' => 'getCountry'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('business_name', $data ?? [], null);
        $this->setIfExists('business_address', $data ?? [], null);
        $this->setIfExists('suburb', $data ?? [], null);
        $this->setIfExists('postcode', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('contact_name', $data ?? [], null);
        $this->setIfExists('contact_number', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['business_name'] === null) {
            $invalidProperties[] = "'business_name' can't be null";
        }
        if ((mb_strlen($this->container['business_name']) > 100)) {
            $invalidProperties[] = "invalid value for 'business_name', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['business_name']) < 2)) {
            $invalidProperties[] = "invalid value for 'business_name', the character length must be bigger than or equal to 2.";
        }

        if ($this->container['business_address'] === null) {
            $invalidProperties[] = "'business_address' can't be null";
        }
        if ((mb_strlen($this->container['business_address']) > 150)) {
            $invalidProperties[] = "invalid value for 'business_address', the character length must be smaller than or equal to 150.";
        }

        if ((mb_strlen($this->container['business_address']) < 5)) {
            $invalidProperties[] = "invalid value for 'business_address', the character length must be bigger than or equal to 5.";
        }

        if ($this->container['suburb'] === null) {
            $invalidProperties[] = "'suburb' can't be null";
        }
        if ((mb_strlen($this->container['suburb']) > 50)) {
            $invalidProperties[] = "invalid value for 'suburb', the character length must be smaller than or equal to 50.";
        }

        if ((mb_strlen($this->container['suburb']) < 2)) {
            $invalidProperties[] = "invalid value for 'suburb', the character length must be bigger than or equal to 2.";
        }

        if ($this->container['postcode'] === null) {
            $invalidProperties[] = "'postcode' can't be null";
        }
        if ((mb_strlen($this->container['postcode']) > 20)) {
            $invalidProperties[] = "invalid value for 'postcode', the character length must be smaller than or equal to 20.";
        }

        if ((mb_strlen($this->container['postcode']) < 2)) {
            $invalidProperties[] = "invalid value for 'postcode', the character length must be bigger than or equal to 2.";
        }

        if ($this->container['state'] === null) {
            $invalidProperties[] = "'state' can't be null";
        }
        if ((mb_strlen($this->container['state']) > 50)) {
            $invalidProperties[] = "invalid value for 'state', the character length must be smaller than or equal to 50.";
        }

        if ((mb_strlen($this->container['state']) < 2)) {
            $invalidProperties[] = "invalid value for 'state', the character length must be bigger than or equal to 2.";
        }

        if ($this->container['contact_name'] === null) {
            $invalidProperties[] = "'contact_name' can't be null";
        }
        if ((mb_strlen($this->container['contact_name']) > 100)) {
            $invalidProperties[] = "invalid value for 'contact_name', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['contact_name']) < 2)) {
            $invalidProperties[] = "invalid value for 'contact_name', the character length must be bigger than or equal to 2.";
        }

        if ($this->container['contact_number'] === null) {
            $invalidProperties[] = "'contact_number' can't be null";
        }
        if (!preg_match("/^\\+?[1-9]\\d{1,14}$/", $this->container['contact_number'])) {
            $invalidProperties[] = "invalid value for 'contact_number', must be conform to the pattern /^\\+?[1-9]\\d{1,14}$/.";
        }

        if ($this->container['country'] === null) {
            $invalidProperties[] = "'country' can't be null";
        }
        if (!preg_match("/^[A-Z]{2}$/", $this->container['country'])) {
            $invalidProperties[] = "invalid value for 'country', must be conform to the pattern /^[A-Z]{2}$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets business_name
     *
     * @return string
     */
    public function getBusinessName()
    {
        return $this->container['business_name'];
    }

    /**
     * Sets business_name
     *
     * @param string $business_name Name of the business (2 - 100 characters)
     *
     * @return self
     */
    public function setBusinessName($business_name)
    {
        if (is_null($business_name)) {
            throw new \InvalidArgumentException('non-nullable business_name cannot be null');
        }
        if ((mb_strlen($business_name) > 100)) {
            throw new \InvalidArgumentException('invalid length for $business_name when calling BuyNumberRequestRegistrationData., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($business_name) < 2)) {
            throw new \InvalidArgumentException('invalid length for $business_name when calling BuyNumberRequestRegistrationData., must be bigger than or equal to 2.');
        }

        $this->container['business_name'] = $business_name;

        return $this;
    }

    /**
     * Gets business_address
     *
     * @return string
     */
    public function getBusinessAddress()
    {
        return $this->container['business_address'];
    }

    /**
     * Sets business_address
     *
     * @param string $business_address Business address (5 - 150 characters)
     *
     * @return self
     */
    public function setBusinessAddress($business_address)
    {
        if (is_null($business_address)) {
            throw new \InvalidArgumentException('non-nullable business_address cannot be null');
        }
        if ((mb_strlen($business_address) > 150)) {
            throw new \InvalidArgumentException('invalid length for $business_address when calling BuyNumberRequestRegistrationData., must be smaller than or equal to 150.');
        }
        if ((mb_strlen($business_address) < 5)) {
            throw new \InvalidArgumentException('invalid length for $business_address when calling BuyNumberRequestRegistrationData., must be bigger than or equal to 5.');
        }

        $this->container['business_address'] = $business_address;

        return $this;
    }

    /**
     * Gets suburb
     *
     * @return string
     */
    public function getSuburb()
    {
        return $this->container['suburb'];
    }

    /**
     * Sets suburb
     *
     * @param string $suburb Suburb/City (2 - 50 characters)
     *
     * @return self
     */
    public function setSuburb($suburb)
    {
        if (is_null($suburb)) {
            throw new \InvalidArgumentException('non-nullable suburb cannot be null');
        }
        if ((mb_strlen($suburb) > 50)) {
            throw new \InvalidArgumentException('invalid length for $suburb when calling BuyNumberRequestRegistrationData., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($suburb) < 2)) {
            throw new \InvalidArgumentException('invalid length for $suburb when calling BuyNumberRequestRegistrationData., must be bigger than or equal to 2.');
        }

        $this->container['suburb'] = $suburb;

        return $this;
    }

    /**
     * Gets postcode
     *
     * @return string
     */
    public function getPostcode()
    {
        return $this->container['postcode'];
    }

    /**
     * Sets postcode
     *
     * @param string $postcode Postal code (2 - 20 characters)
     *
     * @return self
     */
    public function setPostcode($postcode)
    {
        if (is_null($postcode)) {
            throw new \InvalidArgumentException('non-nullable postcode cannot be null');
        }
        if ((mb_strlen($postcode) > 20)) {
            throw new \InvalidArgumentException('invalid length for $postcode when calling BuyNumberRequestRegistrationData., must be smaller than or equal to 20.');
        }
        if ((mb_strlen($postcode) < 2)) {
            throw new \InvalidArgumentException('invalid length for $postcode when calling BuyNumberRequestRegistrationData., must be bigger than or equal to 2.');
        }

        $this->container['postcode'] = $postcode;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string $state State/Province (2 - 50 characters)
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            throw new \InvalidArgumentException('non-nullable state cannot be null');
        }
        if ((mb_strlen($state) > 50)) {
            throw new \InvalidArgumentException('invalid length for $state when calling BuyNumberRequestRegistrationData., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($state) < 2)) {
            throw new \InvalidArgumentException('invalid length for $state when calling BuyNumberRequestRegistrationData., must be bigger than or equal to 2.');
        }

        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets contact_name
     *
     * @return string
     */
    public function getContactName()
    {
        return $this->container['contact_name'];
    }

    /**
     * Sets contact_name
     *
     * @param string $contact_name Contact person name (2 - 100 characters)
     *
     * @return self
     */
    public function setContactName($contact_name)
    {
        if (is_null($contact_name)) {
            throw new \InvalidArgumentException('non-nullable contact_name cannot be null');
        }
        if ((mb_strlen($contact_name) > 100)) {
            throw new \InvalidArgumentException('invalid length for $contact_name when calling BuyNumberRequestRegistrationData., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($contact_name) < 2)) {
            throw new \InvalidArgumentException('invalid length for $contact_name when calling BuyNumberRequestRegistrationData., must be bigger than or equal to 2.');
        }

        $this->container['contact_name'] = $contact_name;

        return $this;
    }

    /**
     * Gets contact_number
     *
     * @return string
     */
    public function getContactNumber()
    {
        return $this->container['contact_number'];
    }

    /**
     * Sets contact_number
     *
     * @param string $contact_number Contact phone number (valid local or international phone number)
     *
     * @return self
     */
    public function setContactNumber($contact_number)
    {
        if (is_null($contact_number)) {
            throw new \InvalidArgumentException('non-nullable contact_number cannot be null');
        }

        if ((!preg_match("/^\\+?[1-9]\\d{1,14}$/", ObjectSerializer::toString($contact_number)))) {
            throw new \InvalidArgumentException("invalid value for \$contact_number when calling BuyNumberRequestRegistrationData., must conform to the pattern /^\\+?[1-9]\\d{1,14}$/.");
        }

        $this->container['contact_number'] = $contact_number;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country Country code (ISO 3166-1 alpha-2)
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }

        if ((!preg_match("/^[A-Z]{2}$/", ObjectSerializer::toString($country)))) {
            throw new \InvalidArgumentException("invalid value for \$country when calling BuyNumberRequestRegistrationData., must conform to the pattern /^[A-Z]{2}$/.");
        }

        $this->container['country'] = $country;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


