<?php
/**
 * MmsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  ClickSend
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ClickSend\Test\Api;

use \ClickSend\Configuration;
use \ClickSend\ApiException;
use \ClickSend\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MmsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ClickSend
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MmsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for calculateMmsPrice
     *
     * Calculate MMS Price.
     *
     */
    public function testCalculateMmsPrice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for exportMmsHistory
     *
     * Export MMS History.
     *
     */
    public function testExportMmsHistory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendMms
     *
     * Send MMS.
     *
     */
    public function testSendMms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for viewMmsHistory
     *
     * View MMS History.
     *
     */
    public function testViewMmsHistory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
