<?php
/**
 * SmsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  ClickSend
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SMS
 *
 * You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ClickSend\Test\Api;

use \ClickSend\Configuration;
use \ClickSend\ApiException;
use \ClickSend\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SmsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ClickSend
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SmsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for calculateSmsPrice
     *
     * Calculate SMS Price.
     *
     */
    public function testCalculateSmsPrice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cancelAllSms
     *
     * Cancel All SMS.
     *
     */
    public function testCancelAllSms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cancelSms
     *
     * Cancel SMS.
     *
     */
    public function testCancelSms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createSmsDeliveryReceiptRule
     *
     * Create SMS Delivery Receipt Rule.
     *
     */
    public function testCreateSmsDeliveryReceiptRule()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createSmsInboundAutomation
     *
     * Create SMS Inbound Automation.
     *
     */
    public function testCreateSmsInboundAutomation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createSmsTemplate
     *
     * Create SMS Template.
     *
     */
    public function testCreateSmsTemplate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createTestInboundSms
     *
     * Create Test Inbound SMS.
     *
     */
    public function testCreateTestInboundSms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createTestSmsReceipt
     *
     * Create Test SMS Receipt.
     *
     */
    public function testCreateTestSmsReceipt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSmsDeliveryReceiptRule
     *
     * Delete SMS Delivery Receipt Rule.
     *
     */
    public function testDeleteSmsDeliveryReceiptRule()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSmsInboundAutomation
     *
     * Delete SMS Inbound Automation.
     *
     */
    public function testDeleteSmsInboundAutomation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSmsTemplate
     *
     * Delete SMS Template.
     *
     */
    public function testDeleteSmsTemplate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for exportSmsHistory
     *
     * Export SMS History.
     *
     */
    public function testExportSmsHistory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for markInboundSmsAsRead
     *
     * Mark Inbound SMS as Read.
     *
     */
    public function testMarkInboundSmsAsRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for markSmsReceiptAsRead
     *
     * Mark SMS Receipt As Read.
     *
     */
    public function testMarkSmsReceiptAsRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for markSpecificInboundSmsMessageAsRead
     *
     * Mark Specific Inbound SMS Message As Read.
     *
     */
    public function testMarkSpecificInboundSmsMessageAsRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendSms
     *
     * Send SMS.
     *
     */
    public function testSendSms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSmsDeliveryReceiptRule
     *
     * Update SMS Delivery Receipt Rule.
     *
     */
    public function testUpdateSmsDeliveryReceiptRule()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSmsInboundAutomation
     *
     * Update SMS Inbound Automation.
     *
     */
    public function testUpdateSmsInboundAutomation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSmsTemplate
     *
     * Update SMS Template.
     *
     */
    public function testUpdateSmsTemplate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for viewASpecificInboundSmsMessage
     *
     * View a specific inbound SMS message.
     *
     */
    public function testViewASpecificInboundSmsMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for viewASpecificSmsTemplate
     *
     * View a Specific SMS Template.
     *
     */
    public function testViewASpecificSmsTemplate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for viewInboundSms
     *
     * View Inbound SMS.
     *
     */
    public function testViewInboundSms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for viewSmsDeliveryReceiptRule
     *
     * View SMS Delivery Receipt Rule.
     *
     */
    public function testViewSmsDeliveryReceiptRule()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for viewSmsDeliveryReceiptRules
     *
     * View SMS Delivery Receipt Rules.
     *
     */
    public function testViewSmsDeliveryReceiptRules()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for viewSmsHistory
     *
     * View SMS History.
     *
     */
    public function testViewSmsHistory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for viewSmsInboundAutomation
     *
     * View SMS Inbound Automation.
     *
     */
    public function testViewSmsInboundAutomation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for viewSmsInboundAutomations
     *
     * View SMS Inbound Automations.
     *
     */
    public function testViewSmsInboundAutomations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for viewSmsReceipts
     *
     * View SMS Receipts.
     *
     */
    public function testViewSmsReceipts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for viewSmsTemplates
     *
     * View SMS Templates.
     *
     */
    public function testViewSmsTemplates()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for viewSpecificSmsReceipt
     *
     * View Specific SMS Receipt.
     *
     */
    public function testViewSpecificSmsReceipt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
